name: Publish JP-Trip site

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository files
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Material for MkDocs
        run: pip install mkdocs-material

      - name: Build and publish site
        run: mkdocs gh-deploy --force
